name: Package exe with PyInstaller - Windows

on:
  push:
    tags:
      - 'v*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: fg_rpc.exe
        path: src/dist/windows/main/main.py # or path/to/artifact

    - uses: softprops/action-gh-release@v1