name: Package exe with PyInstaller - Windows


on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]


#on:
#  push:
#    tags:
#      - 'v*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
        run: python -m pip install --upgrade pip;
          pip install -r requirements.txt;
          pip install pyinstaller;
          cd src;
          pyinstaller main.py --clean -y --onefile;
      
    - uses: actions/upload-artifact@v2
        name: fg_rpc.exe
        path: src/dist/windows/main/main.exe # or path/to/artifact

    #- uses: softprops/action-gh-release@v1
    